// <auto-generated />
using Application.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220527200123_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Application.Entity.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductCode = 3434,
                            ProductName = "Asus-A-100 Laptop",
                            ProductPrice = 5.200m
                        },
                        new
                        {
                            Id = 2,
                            ProductCode = 2345,
                            ProductName = "Arçelik-E-400 Buzdolabı",
                            ProductPrice = 10.500m
                        },
                        new
                        {
                            Id = 3,
                            ProductCode = 3478,
                            ProductName = "Samsung-P-200 LCD Televizyon",
                            ProductPrice = 6.000m
                        },
                        new
                        {
                            Id = 4,
                            ProductCode = 2367,
                            ProductName = "IPhone 13-Akıllı Telefon",
                            ProductPrice = 11.000m
                        },
                        new
                        {
                            Id = 5,
                            ProductCode = 2348,
                            ProductName = "Beko-U-600 Çamaşır Makinesi",
                            ProductPrice = 7.000m
                        });
                });

            modelBuilder.Entity("Application.Entity.Models.Product_Sparepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SparepartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SparepartId");

                    b.ToTable("Product_Spareparts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            SparepartId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            SparepartId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            SparepartId = 3
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            SparepartId = 4
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            SparepartId = 5
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            SparepartId = 6
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 4,
                            SparepartId = 7
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 4,
                            SparepartId = 8
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 5,
                            SparepartId = 9
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            SparepartId = 10
                        });
                });

            modelBuilder.Entity("Application.Entity.Models.Sparepart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("SparePartPrice")
                        .HasColumnType("decimal");

                    b.Property<int>("SparepartCode")
                        .HasColumnType("int");

                    b.Property<string>("SparepartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Spareparts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SparePartPrice = 1.000m,
                            SparepartCode = 6765,
                            SparepartName = "4 GB bilgisayar Ram'i"
                        },
                        new
                        {
                            Id = 2,
                            SparePartPrice = 1.000m,
                            SparepartCode = 7645,
                            SparepartName = "i9 bilgisayar İşlemcisi"
                        },
                        new
                        {
                            Id = 3,
                            SparePartPrice = 1.000m,
                            SparepartCode = 5423,
                            SparepartName = "Buzdolabı Fan Motoru"
                        },
                        new
                        {
                            Id = 4,
                            SparePartPrice = 1.000m,
                            SparepartCode = 9765,
                            SparepartName = "Buzdolabı TelRafı"
                        },
                        new
                        {
                            Id = 5,
                            SparePartPrice = 1.000m,
                            SparepartCode = 3214,
                            SparepartName = "TV Anakartı"
                        },
                        new
                        {
                            Id = 6,
                            SparePartPrice = 1.000m,
                            SparepartCode = 3467,
                            SparepartName = "TV Ayağı Aparatı"
                        },
                        new
                        {
                            Id = 7,
                            SparePartPrice = 1.000m,
                            SparepartCode = 1456,
                            SparepartName = "Telefon Bataryası"
                        },
                        new
                        {
                            Id = 8,
                            SparePartPrice = 1.000m,
                            SparepartCode = 1389,
                            SparepartName = "Telefon Ekranı"
                        },
                        new
                        {
                            Id = 9,
                            SparePartPrice = 1.000m,
                            SparepartCode = 4321,
                            SparepartName = "Çamaşır Makina Kazanı"
                        },
                        new
                        {
                            Id = 10,
                            SparePartPrice = 1.000m,
                            SparepartCode = 4526,
                            SparepartName = "Çamaşır Makine Rezistansı"
                        });
                });

            modelBuilder.Entity("Application.Entity.Models.Product_Sparepart", b =>
                {
                    b.HasOne("Application.Entity.Models.Product", "Product")
                        .WithMany("Product_Spareparts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Entity.Models.Sparepart", "Sparepart")
                        .WithMany("Product_Spareparts")
                        .HasForeignKey("SparepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sparepart");
                });

            modelBuilder.Entity("Application.Entity.Models.Product", b =>
                {
                    b.Navigation("Product_Spareparts");
                });

            modelBuilder.Entity("Application.Entity.Models.Sparepart", b =>
                {
                    b.Navigation("Product_Spareparts");
                });
#pragma warning restore 612, 618
        }
    }
}
